In [20]:
import pandas as pd 

df = pd.read_csv("../tas2_yontem1.csv",encoding="utf-8")
yontem1df = df.copy()
yontem1df['max_price'] = df['max_price'].fillna(df['max_price'].median())
yontem1df['min_price'] = df['min_price'].fillna(df['min_price'].median())
yontem1df['gender'] = df['gender'].fillna("NULL")
yontem1df['message'] = df['message'].fillna("NULL")
yontem1df['comment'] = df['comment'].fillna("NULL")
yontem1df['deviceType'] = df['deviceType'].fillna("NULL")
yontem1df['categories'] = df['categories'].fillna("NULL")
yontem1df['contents'] = df['contents'].fillna("NULL")
df = yontem1df.copy()

df

,categories,contents,pageDuration,title,url,clicks,focusLossCount,sessionDuration,deviceType,comment,message,min_price,gender,max_price
0,NULL,NULL,13000,Beautiful Demo Page,http://localhost:8088/,83,133,36422086,mobile,NULL,NULL,661.5,NULL,500.0
1,NULL,NULL,616000,Beautiful Demo Page,http://localhost:8088/,83,133,36422086,mobile,NULL,NULL,661.5,NULL,500.0
2,NULL,NULL,46000,Beautiful Demo Page,http://localhost:8088/,83,133,36422086,mobile,NULL,NULL,661.5,NULL,500.0
3,NULL,NULL,48000,Beautiful Demo Page,http://localhost:8088/,83,133,36422086,mobile,NULL,NULL,661.5,NULL,500.0
4,NULL,NULL,39000,Beautiful Demo Page,http://localhost:8088/,83,133,36422086,mobile,NULL,NULL,661.5,NULL,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,NULL,NULL,6001,Beautiful Demo Page,http://localhost:8088/,43,19,9552482,tablet,NULL,NULL,661.5,NULL,500.0
103,book2,NULL,196000,Beautiful Demo Page,http://localhost:8088/,43,19,9552482,tablet,NULL,NULL,123.0,male,500.0
104,akali,NULL,196000,Beautiful Demo Page,http://localhost:8088/,43,19,9552482,tablet,NULL,NULL,123.0,male,500.0
105,NULL,NULL,1323,Beautiful Demo Page,http://localhost:8088/,43,19,9552482,tablet,NULL,NULL,661.5,NULL,500.0
106,book2,NULL,66000,Beautiful Demo Page,http://localhost:8088/,43,19,9552482,tablet,a,NULL,661.5,NULL,500.0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   categories       107 non-null    object
 1   contents         107 non-null    object
 2   pageDuration     107 non-null    int64
 3   title            107 non-null    object
 4   url              107 non-null    object
 5   clicks           107 non-null    int64
 6   focusLossCount   107 non-null    int64
 7   sessionDuration  107 non-null    int64
 8   deviceType       107 non-null    object
 9   comment          107 non-null    object
 10  message          107 non-null    object
 11  min_price        107 non-null    float64
 12  gender           107 non-null    object
 13  max_price        107 non-null    float64
dtypes: float64(2), int64(4), object(8)
memory usage: 11.8+ KB

In [21]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.cluster import KMeans

numerical_features = df.select_dtypes(include=['float64', 'int64']).columns

categorical_features = df.select_dtypes(include=['object']).columns

ss = StandardScaler()
ohe = OneHotEncoder(handle_unknown='ignore')
preprocessor = ColumnTransformer(
    transformers=[
        ('num', ss, numerical_features),
        ('cat', ohe, categorical_features)
    ]
)

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('clusterer', KMeans(n_clusters=2, random_state=42))
])
pipeline.fit(df)
labels = pipeline.named_steps['clusterer'].labels_
df['segment'] = labels

df

,categories,contents,pageDuration,title,url,clicks,focusLossCount,sessionDuration,deviceType,comment,message,min_price,gender,max_price,segment
0,NULL,NULL,13000,Beautiful Demo Page,http://localhost:8088/,83,133,36422086,mobile,NULL,NULL,661.5,NULL,500.0,0
1,NULL,NULL,616000,Beautiful Demo Page,http://localhost:8088/,83,133,36422086,mobile,NULL,NULL,661.5,NULL,500.0,0
2,NULL,NULL,46000,Beautiful Demo Page,http://localhost:8088/,83,133,36422086,mobile,NULL,NULL,661.5,NULL,500.0,0
3,NULL,NULL,48000,Beautiful Demo Page,http://localhost:8088/,83,133,36422086,mobile,NULL,NULL,661.5,NULL,500.0,0
4,NULL,NULL,39000,Beautiful Demo Page,http://localhost:8088/,83,133,36422086,mobile,NULL,NULL,661.5,NULL,500.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,NULL,NULL,6001,Beautiful Demo Page,http://localhost:8088/,43,19,9552482,tablet,NULL,NULL,661.5,NULL,500.0,1
103,book2,NULL,196000,Beautiful Demo Page,http://localhost:8088/,43,19,9552482,tablet,NULL,NULL,123.0,male,500.0,1
104,akali,NULL,196000,Beautiful Demo Page,http://localhost:8088/,43,19,9552482,tablet,NULL,NULL,123.0,male,500.0,1
105,NULL,NULL,1323,Beautiful Demo Page,http://localhost:8088/,43,19,9552482,tablet,NULL,NULL,661.5,NULL,500.0,1
106,book2,NULL,66000,Beautiful Demo Page,http://localhost:8088/,43,19,9552482,tablet,a,NULL,661.5,NULL,500.0,1

In [23]:
import joblib
joblib.dump(pipeline, 'kmeans_segment2.pkl')

['kmeans_segment2.pkl']